[project]
name = "drone-cp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "shapely>=2.0.0",
    "pyproj>=3.5.0",
    "matplotlib>=3.6.0",
    "neo4j>=5.0.0",
]
