[project]
name = "drone-cp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash>=3.3.0",
    "neo4j>=5.0.0",
    "numpy>=2.2.6",
]
